# Use postgres/example user/password credentials
#
# ATEÇÃO: 
# este compose eh eh utilizado apenas quando queremos containerizar APENAS o POSTGRESQL.
# Caso deseja containerizar a aplicacao inteira, acesse o diretorio:  /src/main/docker  e execute o procedimento comentado dentro do docker-compose.
#


version: '3.1'

services:

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=passroot
      - POSTGRES_USER=useradmin
      - POSTGRES_DB=usermanagerdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080