# Use postgres/example user/password credentials

# docker run --name postgresdb -e POSTGRES_PASSWORD=mysecretpassword -d postgres

version: '3.1'

services:

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=passroot
      - POSTGRES_USER=useradmin
      - POSTGRES_DB=usermanagerdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080